### ISSUE TITLE
Listed extension - allow anonymous share

### ISSUE THREAD

**Issue by mobitar** [standardnotes/contribute#2]
The Listed extension currently allows you to publish notes and receive a shareable link. The links however are currently vanity links (i.e listed.standardnotes.org/a-note-im-sharing, and are not very private. Instead, many users have requested that these URLs be sufficiently random, and use a long token instead of a vanity URL.

Repo: https://github.com/standardnotes/listed

Experience you'll probably need:
Ruby, Rails

**Comment by ryanpcmcquen** [comment]
The `Publish Unlisted` option closes this, right?

https://listed.standardnotes.org/4qhKDPF

Or do users want an even longer token?

**Comment by mobitar** [comment]
Well, you were the user that requested this ;) https://forum.standardnotes.org/d/64-two-small-feature-requests/2

**Comment by ryanpcmcquen** [comment]
That request is for _unpublishing_ a note, not publishing the note unlisted.

**Comment by mobitar** [comment]
You can now unpublish notes.

**Comment by ryanpcmcquen** [comment]
That's beautiful! Is the only publishing option now with a hash for the URL? Before you could generate vanity URLs (not that I really ever planned to use that), but I just want to make sure I am understanding the functionality.

**Comment by mobitar** [comment]
Correct, only random tokens. The idea before was to create a sort of blog setting for users where they can publish to their profiles. Not that I'm totally abandoning this idea, but it was too soon for it. First enough people need to just share anonymously, then when usage picks up, we can re-introduce vanity urls and profile publishing, etc.
